services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  ingester:
    build:
      context: .
      dockerfile: Dockerfile.ingester
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ../../sample_data:/data
    environment:
      DB_FILE_PATH: /data/scraper_results.db
    command: uvicorn ingester:app --host 0.0.0.0 --port 8000

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      REDIS_CONNECTION_STRING: redis://redis:6379
      TWITTER_SESSION_COOKIE: ${TWITTER_SESSION_COOKIE}
      TWITTER_USERNAME: ${TWITTER_USERNAME}
      TWITTER_EMAIL: ${TWITTER_EMAIL}
      RESULTS_ENDPOINT: http://ingester:8000/data/scraper
    command: celery -A tasks worker -B --loglevel=info
