FROM python:3.11

WORKDIR /app

# Install Poetry
RUN pip install poetry

# Copy only the necessary files to export dependencies with Poetry
COPY pyproject.toml poetry.lock ./

# Export dependencies to requirements.txt
RUN poetry export --without-hashes --format=requirements.txt > requirements.txt

# Install dependencies from requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
