FROM python:3.11

WORKDIR /app

# Install Poetry
RUN pip install poetry

# Copy only the necessary files to install dependencies with Poetry
COPY pyproject.toml poetry.lock ./

# Install dependencies using Poetry
RUN poetry config virtualenvs.create false && poetry install --only main --no-interaction --no-ansi

# Download necessary NLTK data
RUN python -m nltk.downloader vader_lexicon movie_reviews punkt

COPY examples/combined /app
