FROM python:3.11

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN python -m nltk.downloader vader_lexicon movie_reviews punkt
# RUN python -m nltk.downloader all

COPY . .
